### ISSUE TITLE
Publish plugin dependencies to jcenter

### ISSUE THREAD

**Issue by Nimrodda** [Nimrodda/buildmetrics-gradle-plugin#7]

**Comment by martinbonnin** [comment]
Why not publish the plugin to the gradle plugin portal ? It's available by default in gradle.

**Comment by Nimrodda** [comment]
The plugins are published to Gradle plugin portal, but there're also library dependencies, such as `buildmetrics-common` and `buildmetrics-db` that currently are published to bintray. Do you know if those can also be published to Gradle plugin portal?

**Comment by martinbonnin** [comment]
I had the same question 😅
